from nicegui import app

# Internationalization (i18n)
i18n = {
    "api_management": {"en": "API Management", "zh": "API 管理", "ko": "API 관리", "ja": "API管理"},
    "dashboard": {"en": "Dashboard", "zh": "儀表板", "ko": "대시보드", "ja": "ダッシュボード"},
    "providers": {"en": "Providers", "zh": "供應商", "ko": "공급자", "ja": "プロバイダー"},
    "groups": {"en": "Groups", "zh": "群組", "ko": "그룹", "ja": "グループ"},
    "call_logs": {"en": "Call Logs", "zh": "呼叫日誌", "ko": "호출 로그", "ja": "コールログ"},
    "failure_keywords": {"en": "Failure Keywords", "zh": "失敗關鍵字", "ko": "실패 키워드", "ja": "失敗キーワード"},
    "api_keys": {"en": "API Keys", "zh": "API 金鑰", "ko": "API 키", "ja": "APIキー"},
    "logout": {"en": "Logout", "zh": "登出", "ko": "로그아웃", "ja": "ログアウト"},
    "login": {"en": "Login", "zh": "登入", "ko": "로그인", "ja": "ログイン"},
    "username": {"en": "Username", "zh": "使用者名稱", "ko": "사용자 이름", "ja": "ユーザー名"},
    "password": {"en": "Password", "zh": "密碼", "ko": "비밀번호", "ja": "パスワード"},
    "niceapi_title": {"en": "NiceAPI", "zh": "NiceAPI", "ko": "NiceAPI", "ja": "NiceAPI"},
    "niceapi_subtitle": {"en": "Insightful Data, Driven Decisions", "zh": "深入洞察，驅動決策", "ko": "통찰력 있는 데이터, 데이터 기반 의사결정", "ja": "洞察力のあるデータ、データ駆動の意思決定"},
    "copyright": {"en": "© 2025 NiceAPI. All rights reserved.", "zh": "© 2025 NiceAPI. 版權所有。", "ko": "© 2025 NiceAPI. 모든 권리 보유.", "ja": "© 2025 NiceAPI. 全著作権所有。"},
    "model_usage_distribution": {"en": "Model Usage Distribution", "zh": "模型使用分佈", "ko": "모델 사용 분포", "ja": "モデル使用分布"},
    "api_calls": {"en": "API Calls", "zh": "API 呼叫", "ko": "API 호출", "ja": "API呼び出し"},
    "no_api_call_data": {"en": "No API call data available.", "zh": "沒有可用的 API 呼叫資料。", "ko": "API 호출 데이터가 없습니다.", "ja": "APIコールデータがありません。"},
    "daily_api_calls": {"en": "Daily API Calls (Last 7 Days)", "zh": "每日 API 呼叫 (最近 7 天)", "ko": "일일 API 호출 (최근 7일)", "ja": "毎日のAPIコール (過去7日間)"},
    "no_recent_api_call_data": {"en": "No recent API call data available.", "zh": "最近沒有 API 呼叫資料。", "ko": "최근 API 호출 데이터가 없습니다.", "ja": "最近のAPIコールデータはありません。"},
    "api_call_success_rate": {"en": "API Call Success Rate", "zh": "API 呼叫成功率", "ko": "API 호출 성공률", "ja": "APIコール成功率"},
    "successful": {"en": "Successful", "zh": "成功", "ko": "성공", "ja": "成功"},
    "failed": {"en": "Failed", "zh": "失敗", "ko": "실패", "ja": "失敗"},
    "avg_response_time_ms": {"en": "Avg. Response Time (ms)", "zh": "平均回應時間 (毫秒)", "ko": "평균 응답 시간 (ms)", "ja": "平均応答時間 (ms)"},
    "no_successful_calls_with_response_time": {"en": "No successful calls with response time data.", "zh": "沒有帶有回應時間資料的成功呼叫。", "ko": "응답 시간 데이터가 있는 성공적인 호출이 없습니다.", "ja": "応答時間データのある成功した呼び出しはありません。"},
    "api_endpoint_success_rate": {"en": "API Endpoint Success Rate", "zh": "API 端點成功率", "ko": "API 엔드포인트 성공률", "ja": "APIエンドポイント成功率"},
    "no_data_for_endpoint_success_rate": {"en": "No data for endpoint success rate.", "zh": "沒有端點成功率資料。", "ko": "엔드포인트 성공률에 대한 데이터가 없습니다.", "ja": "エンドポイント成功率のデータがありません。"},
    "avg_response_time_by_endpoint_ms": {"en": "Avg. Response Time by Endpoint (ms)", "zh": "各端點平均回應時間 (毫秒)", "ko": "엔드포인트별 평균 응답 시간 (ms)", "ja": "エンドポイント別の平均応答時間 (ms)"},
    "total_api_calls_by_endpoint": {"en": "Total API Calls by Endpoint", "zh": "各端點總 API 呼叫數", "ko": "엔드포인트별 총 API 호출 수", "ja": "エンドポイント別の合計APIコール数"},
    "total_cost_by_model": {"en": "Total Cost by Model ($)", "zh": "各模型總成本 ($)", "ko": "모델별 총 비용 ($)", "ja": "モデル別の総コスト ($)"},
    "no_cost_data": {"en": "No cost data available.", "zh": "沒有成本資料。", "ko": "비용 데이터가 없습니다.", "ja": "コストデータがありません。"},
    "refresh_data": {"en": "Refresh Data", "zh": "重新整理資料", "ko": "데이터 새로고침", "ja": "データを更新"},
    "add_provider": {"en": "Add Provider", "zh": "新增供應商", "ko": "공급자 추가", "ja": "プロバイダーを追加"},
    "import_from_url": {"en": "Import From URL", "zh": "從 URL 匯入", "ko": "URL에서 가져오기", "ja": "URLからインポート"},
    "quick_remove": {"en": "Quick Remove", "zh": "快速移除", "ko": "빠른 제거", "ja": "クイック削除"},
    "add_new_provider": {"en": "Add New Provider", "zh": "新增供應商", "ko": "새 공급자 추가", "ja": "新しいプロバイダーを追加"},
    "name": {"en": "Name", "zh": "名稱", "ko": "이름", "ja": "名前"},
    "api_endpoint": {"en": "API Endpoint", "zh": "API 端點", "ko": "API 엔드포인트", "ja": "APIエンドポイント"},
    "api_key": {"en": "API Key", "zh": "API 金鑰", "ko": "API 키", "ja": "APIキー"},
    "model": {"en": "Model", "zh": "模型", "ko": "모델", "ja": "モデル"},
    "price_per_million_tokens": {"en": "Price/Million Tokens", "zh": "每百萬權杖價格", "ko": "백만 토큰당 가격", "ja": "100万トークンあたりの価格"},
    "type": {"en": "Type", "zh": "類型", "ko": "유형", "ja": "タイプ"},
    "active": {"en": "Active", "zh": "啟用", "ko": "활성", "ja": "アクティブ"},
    "add": {"en": "Add", "zh": "新增", "ko": "추가", "ja": "追加"},
    "cancel": {"en": "Cancel", "zh": "取消", "ko": "취소", "ja": "キャンセル"},
    "provider_added": {"en": "Provider \"{name}\" added!", "zh": "已新增供應商「{name}」！", "ko": "\"{name}\" 공급자가 추가되었습니다!", "ja": "プロバイダー「{name}」が追加されました！"},
    "import_models_from_url": {"en": "Import Models from URL", "zh": "從 URL 匯入模型", "ko": "URL에서 모델 가져오기", "ja": "URLからモデルをインポート"},
    "base_url": {"en": "Base URL", "zh": "基礎 URL", "ko": "기본 URL", "ja": "ベースURL"},
    "alias_optional": {"en": "Alias (Optional)", "zh": "別名 (可選)", "ko": "별칭 (선택 사항)", "ja": "エイリアス (任意)"},
    "default_type": {"en": "Default Type", "zh": "預設類型", "ko": "기본 유형", "ja": "デフォルトタイプ"},
    "filter_mode": {"en": "Filter Mode", "zh": "篩選模式", "ko": "필터 모드", "ja": "フィルターモード"},
    "model_name_filter": {"en": "Model Name Filter", "zh": "模型名稱篩選器", "ko": "모델 이름 필터", "ja": "モデル名フィルター"},
    "import": {"en": "Import", "zh": "匯入", "ko": "가져오기", "ja": "インポート"},
    "quick_remove_by_api_key": {"en": "Quick Remove by API Key", "zh": "依 API 金鑰快速移除", "ko": "API 키로 빠른 제거", "ja": "APIキーでクイック削除"},
    "remove": {"en": "Remove", "zh": "移除", "ko": "제거", "ja": "削除"},
    "edit_provider": {"en": "Edit Provider", "zh": "編輯供應商", "ko": "공급자 편집", "ja": "プロバイダーを編集"},
    "save": {"en": "Save", "zh": "儲存", "ko": "저장", "ja": "保存"},
    "provider_updated": {"en": "Provider \"{name}\" updated!", "zh": "已更新供應商「{name}」！", "ko": "\"{name}\" 공급자가 업데이트되었습니다!", "ja": "プロバイダー「{name}」が更新されました！"},
    "delete_provider_confirm": {"en": "Are you sure you want to delete provider '{name}'?", "zh": "您確定要刪除供應商「{name}」嗎？", "ko": "'{name}' 공급자를 삭제하시겠습니까?", "ja": "プロバイダー「{name}」を削除してもよろしいですか？"},
    "delete": {"en": "Delete", "zh": "刪除", "ko": "삭제", "ja": "削除"},
    "provider_deleted": {"en": "Provider '{name}' deleted.", "zh": "已刪除供應商「{name}」。", "ko": "'{name}' 공급자가 삭제되었습니다.", "ja": "プロバイダー「{name}」が削除されました。"},
    "id": {"en": "ID", "zh": "ID", "ko": "ID", "ja": "ID"},
    "price_dollar_per_1m": {"en": "Price ($/1M)", "zh": "價格 ($/百萬)", "ko": "가격 ($/1M)", "ja": "価格 ($/1M)"},
    "actions": {"en": "Actions", "zh": "操作", "ko": "작업", "ja": "アクション"},
    "provider_groups": {"en": "Provider Groups", "zh": "供應商群組", "ko": "공급자 그룹", "ja": "プロバイダーグループ"},
    "groups_description": {"en": "Group providers together to create custom pools for model requests.", "zh": "將供應商分組以建立自訂的模型請求池。", "ko": "공급자들을 그룹으로 묶어 모델 요청을 위한 맞춤형 풀을 생성합니다.", "ja": "プロバイダーをグループ化して、モデルリクエスト用のカスタムプールを作成します。"},
    "create_new_group": {"en": "Create New Group", "zh": "建立新群組", "ko": "새 그룹 만들기", "ja": "新しいグループを作成"},
    "group_name": {"en": "Group Name", "zh": "群組名稱", "ko": "그룹 이름", "ja": "グループ名"},
    "group_name_empty_error": {"en": "Group name cannot be empty.", "zh": "群組名稱不能為空。", "ko": "그룹 이름은 비워 둘 수 없습니다.", "ja": "グループ名は空にできません。"},
    "group_exists_error": {"en": "Group '{name}' already exists.", "zh": "群組「{name}」已存在。", "ko": "'{name}' 그룹이 이미 존재합니다.", "ja": "グループ「{name}」は既に存在します。"},
    "group_created": {"en": "Group '{name}' created.", "zh": "已建立群組「{name}」。", "ko": "'{name}' 그룹이 생성되었습니다.", "ja": "グループ「{name}」が作成されました。"},
    "create": {"en": "Create", "zh": "建立", "ko": "만들기", "ja": "作成"},
    "create_group": {"en": "Create Group", "zh": "建立群組", "ko": "그룹 만들기", "ja": "グループを作成"},
    "refresh_groups": {"en": "Refresh Groups", "zh": "重新整理群組", "ko": "그룹 새로고침", "ja": "グループを更新"},
    "no_groups_created": {"en": "No groups created yet.", "zh": "尚未建立任何群組。", "ko": "아직 생성된 그룹이 없습니다.", "ja": "まだグループが作成されていません。"},
    "group_id": {"en": "Group ID", "zh": "群組 ID", "ko": "그룹 ID", "ja": "グループID"},
    "delete_group_confirm": {"en": "Are you sure you want to delete the group '{name}'?", "zh": "您確定要刪除群組「{name}」嗎？", "ko": "'{name}' 그룹을 삭제하시겠습니까?", "ja": "グループ「{name}」を削除してもよろしいですか？"},
    "group_deleted": {"en": "Group '{name}' deleted.", "zh": "已刪除群組「{name}」。", "ko": "'{name}' 그룹이 삭제되었습니다.", "ja": "グループ「{name}」が削除されました。"},
    "priority": {"en": "Priority", "zh": "優先級", "ko": "우선순위", "ja": "優先度"},
    "save_changes": {"en": "Save Changes", "zh": "儲存變更", "ko": "변경 내용 저장", "ja": "変更を保存"},
    "group_updated": {"en": "Group '{name}' updated.", "zh": "已更新群組「{name}」。", "ko": "'{name}' 그룹이 업데이트되었습니다.", "ja": "グループ「{name}」が更新されました。"},
    "no_changes_to_save": {"en": "No changes to save.", "zh": "沒有要儲存的變更。", "ko": "저장할 변경 사항이 없습니다.", "ja": "保存する変更はありません。"},
    "refresh_logs": {"en": "Refresh Logs", "zh": "重新整理日誌", "ko": "로그 새로고침", "ja": "ログを更新"},
    "timestamp": {"en": "Timestamp", "zh": "時間戳", "ko": "타임스탬프", "ja": "タイムスタンプ"},
    "success": {"en": "Success", "zh": "成功", "ko": "성공", "ja": "成功"},
    "status": {"en": "Status", "zh": "狀態", "ko": "상태", "ja": "ステータス"},
    "response_time_ms": {"en": "Response Time (ms)", "zh": "回應時間 (毫秒)", "ko": "응답 시간 (ms)", "ja": "応答時間 (ms)"},
    "prompt_tokens": {"en": "Prompt Tokens", "zh": "提示權杖", "ko": "프롬프트 토큰", "ja": "プロンプトトークン"},
    "completion_tokens": {"en": "Completion Tokens", "zh": "完成權杖", "ko": "완성 토큰", "ja": "完了トークン"},
    "total_tokens": {"en": "Total Tokens", "zh": "總權杖", "ko": "총 토큰", "ja": "合計トークン"},
    "cost": {"en": "Cost ($)", "zh": "成本 ($)", "ko": "비용 ($)", "ja": "コスト ($)"},
    "error": {"en": "Error", "zh": "錯誤", "ko": "오류", "ja": "エラー"},
    "failure_keywords_description": {"en": "Define keywords that indicate a failed API response, even with a 200 status code.", "zh": "定義關鍵字，用於標識即使狀態碼為 200 也算失敗的 API 回應。", "ko": "200 상태 코드에도 불구하고 실패한 API 응답을 나타내는 키워드를 정의합니다.", "ja": "ステータスコードが200であっても、失敗したAPI応答を示すキーワードを定義します。"},
    "add_failure_keyword": {"en": "Add Failure Keyword", "zh": "新增失敗關鍵字", "ko": "실패 키워드 추가", "ja": "失敗キーワードを追加"},
    "keyword_case_insensitive": {"en": "Keyword (case-insensitive)", "zh": "關鍵字 (不區分大小寫)", "ko": "키워드 (대소문자 무시)", "ja": "キーワード (大文字と小文字を区別しない)"},
    "description": {"en": "Description", "zh": "描述", "ko": "설명", "ja": "説明"},
    "keyword_added": {"en": "Keyword \"{keyword}\" added.", "zh": "已新增關鍵字「{keyword}」。", "ko": "\"{keyword}\" 키워드가 추가되었습니다.", "ja": "キーワード「{keyword}」が追加されました。"},
    "add_keyword": {"en": "Add Keyword", "zh": "新增關鍵字", "ko": "키워드 추가", "ja": "キーワードを追加"},
    "keyword": {"en": "Keyword", "zh": "關鍵字", "ko": "키워드", "ja": "キーワード"},
    "last_triggered": {"en": "Last Triggered", "zh": "上次觸發", "ko": "마지막 트리거", "ja": "最終トリガー"},
    "delete_keyword_confirm": {"en": "Delete keyword '{keyword}'?", "zh": "確定要刪除關鍵字「{keyword}」嗎？", "ko": "'{keyword}' 키워드를 삭제하시겠습니까?", "ja": "キーワード「{keyword}」を削除しますか？"},
    "keyword_deleted": {"en": "Keyword '{keyword}' deleted.", "zh": "已刪除關鍵字「{keyword}」。", "ko": "'{keyword}' 키워드가 삭제되었습니다.", "ja": "キーワード「{keyword}」が削除されました。"},
    "api_keys_description": {"en": "Manage API keys for accessing different services.", "zh": "管理用於存取不同服務的 API 金鑰。", "ko": "다양한 서비스에 액세스하기 위한 API 키를 관리합니다.", "ja": "さまざまなサービスにアクセスするためのAPIキーを管理します。"},
    "add_api_key": {"en": "Add API Key", "zh": "新增 API 金鑰", "ko": "API 키 추가", "ja": "APIキーを追加"},
    "api_key_name": {"en": "API Key Name", "zh": "API 金鑰名稱", "ko": "API 키 이름", "ja": "APIキー名"},
    "api_key_value": {"en": "API Key Value", "zh": "API 金鑰值", "ko": "API 키 값", "ja": "APIキーの値"},
    "key_added": {"en": "API Key \"{name}\" added.", "zh": "已新增 API 金鑰「{name}」。", "ko": "API 키 \"{name}\"이(가) 추가되었습니다.", "ja": "APIキー「{name}」が追加されました。"},
    "delete_key_confirm": {"en": "Delete API Key '{name}'?", "zh": "確定要刪除 API 金鑰「{name}」嗎？", "ko": "API 키 '{name}'을(를) 삭제하시겠습니까?", "ja": "APIキー「{name}」を削除しますか？"},
    "key_deleted": {"en": "API Key '{name}' deleted.", "zh": "已刪除 API 金鑰「{name}」。", "ko": "API 키 '{name}'이(가) 삭제되었습니다.", "ja": "APIキー「{name}」が削除されました。"},
    "key_name": {"en": "Key Name", "zh": "金鑰名稱", "ko": "키 이름", "ja": "キー名"},
    "create_api_key": {"en": "Create API Key", "zh": "建立 API 金鑰", "ko": "API 키 만들기", "ja": "APIキーを作成"},
    "api_key_generated_successfully": {"en": "API Key Generated Successfully", "zh": "API 金鑰已成功產生", "ko": "API 키가 성공적으로 생성되었습니다", "ja": "APIキーが正常に生成されました"},
    "copy_key_instruction": {"en": "Please copy this key. You will not be able to see it again.", "zh": "請複製此金鑰。您將無法再次看到它。", "ko": "이 키를 복사하십시오. 다시는 볼 수 없습니다.", "ja": "このキーをコピーしてください。二度と表示されません。"},
    "your_new_api_key": {"en": "Your New API Key", "zh": "您的新 API 金鑰", "ko": "새 API 키", "ja": "新しいAPIキー"},
    "copied_to_clipboard": {"en": "Copied to clipboard!", "zh": "已複製到剪貼簿！", "ko": "클립보드에 복사되었습니다!", "ja": "クリップボードにコピーされました！"},
    "copy_tooltip": {"en": "Copy to clipboard", "zh": "複製到剪貼簿", "ko": "클립보드에 복사", "ja": "クリップボードにコピー"},
    "close": {"en": "Close", "zh": "關閉", "ko": "닫기", "ja": "閉じる"},
    "create_new_api_key": {"en": "Create New API Key", "zh": "建立新的 API 金鑰", "ko": "새 API 키 만들기", "ja": "新しいAPIキーを作成"},
    "assign_to_groups": {"en": "Assign to Groups", "zh": "分配到群組", "ko": "그룹에 할당", "ja": "グループに割り当て"},
    "assign_to_at_least_one_group_error": {"en": "An API key must be assigned to at least one group.", "zh": "API 金鑰必須至少分配到一個群組。", "ko": "API 키는 하나 이상의 그룹에 할당되어야 합니다.", "ja": "APIキーは少なくとも1つのグループに割り当てる必要があります。"},
    "api_key_created": {"en": "API Key created!", "zh": "API 金鑰已建立！", "ko": "API 키가 생성되었습니다!", "ja": "APIキーが作成されました！"},
    "key": {"en": "Key", "zh": "金鑰", "ko": "키", "ja": "キー"},
    "created_at": {"en": "Created At", "zh": "建立於", "ko": "생성일", "ja": "作成日"},
    "last_used": {"en": "Last Used", "zh": "上次使用", "ko": "마지막 사용", "ja": "最終使用日"},
    "never": {"en": "Never", "zh": "從不", "ko": "없음", "ja": "なし"},
    "edit_api_key": {"en": "Edit API Key", "zh": "編輯 API 金鑰", "ko": "API 키 편집", "ja": "APIキーを編集"},
    "assigned_groups": {"en": "Assigned Groups", "zh": "已分配的群組", "ko": "할당된 그룹", "ja": "割り当てられたグループ"},
    "api_key_updated": {"en": "API Key updated!", "zh": "API 金鑰已更新！", "ko": "API 키가 업데이트되었습니다!", "ja": "APIキーが更新されました！"},
    "api_key_status_changed": {"en": "API Key status changed.", "zh": "API 金鑰狀態已變更。", "ko": "API 키 상태가 변경되었습니다.", "ja": "APIキーのステータスが変更されました。"},
    "delete_api_key_confirm": {"en": "Are you sure you want to delete the key {key_display}?", "zh": "您確定要刪除金鑰 {key_display} 嗎？", "ko": "키 {key_display}을(를) 삭제하시겠습니까?", "ja": "キー {key_display} を削除してもよろしいですか？"},
    "api_key_deleted": {"en": "API Key deleted.", "zh": "API 金鑰已刪除。", "ko": "API 키가 삭제되었습니다.", "ja": "APIキーが削除されました。"},
    "settings": {"en": "Settings", "zh": "設定", "ko": "설정", "ja": "設定"},
    "failover_settings": {"en": "Failover Settings", "zh": "故障轉移設定", "ko": "장애 조치 설정", "ja": "フェイルオーバー設定"},
    "failover_description": {"en": "Configure the conditions under which the system will automatically failover to a backup provider.", "zh": "設定系統自動故障轉移到備用供應商的條件。", "ko": "시스템이 백업 공급자로 자동 장애 조치되는 조건을 구성합니다.", "ja": "システムがバックアッププロバイダーに自動的にフェイルオーバーする条件を設定します。"},
    "failure_count_threshold": {"en": "Failure Count Threshold", "zh": "失敗次數閾值", "ko": "실패 횟수 임계값", "ja": "失敗回数のしきい値"},
    "failure_period_minutes": {"en": "Failure Period (minutes)", "zh": "失敗期間 (分鐘)", "ko": "실패 기간 (분)", "ja": "失敗期間 (分)"},
    "settings_saved": {"en": "Settings saved successfully.", "zh": "設定已成功儲存。", "ko": "설정이 성공적으로 저장되었습니다.", "ja": "設定が正常に保存されました。"},
    "response_body": {"en": "Response Body", "zh": "回應內文", "ko": "응답 본문", "ja": "応答本文"},
    "view": {"en": "View", "zh": "查看", "ko": "보기", "ja": "表示"},
    "dashboard_refreshed": {"en": "Dashboard refreshed!", "zh": "儀表板已刷新！", "ko": "대시보드가 새로 고쳐졌습니다!", "ja": "ダッシュボードが更新されました！"},
    "groups_view_refreshed": {"en": "Groups view refreshed!", "zh": "群組視圖已刷新！", "ko": "그룹 보기가 새로 고쳐졌습니다!", "ja": "グループビューが更新されました！"},
    "logs_refreshed": {"en": "Logs refreshed!", "zh": "日誌已刷新！", "ko": "로그가 새로 고쳐졌습니다!", "ja": "ログが更新されました！"},
    "group_list_refreshed": {"en": "Group list refreshed", "zh": "群組列表已刷新", "ko": "그룹 목록이 새로 고쳐졌습니다", "ja": "グループリストが更新されました"},
    "providers_refreshed": {"en": "Providers refreshed!", "zh": "供應商已刷新！", "ko": "공급자가 새로 고쳐졌습니다!", "ja": "プロバイダーが更新されました！"},
    "api_keys_refreshed": {"en": "API keys refreshed!", "zh": "API 金鑰已刷新！", "ko": "API 키가 새로 고쳐졌습니다!", "ja": "APIキーが更新されました！"},
    "keywords_refreshed": {"en": "Keywords refreshed!", "zh": "關鍵字已刷新！", "ko": "키워드가 새로 고쳐졌습니다!", "ja": "キーワードが更新されました！"},
    "refresh_providers": {"en": "Refresh Providers", "zh": "重新整理供應商", "ko": "공급자 새로고침", "ja": "プロバイダーを更新"},
    "refresh_api_keys": {"en": "Refresh API Keys", "zh": "重新整理 API 金鑰", "ko": "API 키 새로고침", "ja": "APIキーを更新"},
    "refresh_keywords": {"en": "Refresh Keywords", "zh": "重新整理關鍵字", "ko": "키워드 새로고침", "ja": "キーワードを更新"},
}

def get_text(key: str) -> str:
    """Gets the translated text for a given key."""
    lang = app.storage.user.get('lang', 'en')
    return i18n.get(key, {}).get(lang, i18n.get(key, {}).get('en', key))